/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admision;

import Herramientas.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luis
 */
public class Agregar_Ciudad extends javax.swing.JFrame {

    DefaultTableModel model;

    /**
     * Creates new form Agregar_Ciudad
     */
    public Agregar_Ciudad() {
        initComponents();
        cargar("");
    }

    void cargar(String sValor) {
        String[] titulos = {"Numero Ciudad", "Nombre"};
        String[] registros = new String[2];

        String sql = "SELECT * FROM albergue_sanvicente.admision_ciudad WHERE CONCAT( idCiudad, ' ', Nombre)LIKE '%" + sValor + "%'";
        model = new DefaultTableModel(null, titulos);
        conectar cc = new conectar();
        Connection cn = cc.conexion();

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                registros[0] = rs.getString("idCiudad");
                registros[1] = rs.getString("Nombre");

                model.addRow(registros);
            }
            tblRegistros.setModel(model);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    public int ControlLlavePrimaria() {
        int i = 1;
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String sql = "SELECT MAX(idCiudad) as NumMaximo FROM admision_ciudad";
        try {
            java.sql.Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                i = rs.getInt("NumMaximo");
            }
            cn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al Consultar tipo " + ex);
            ex.printStackTrace();
        }
        return i + 1;

    }

    public void GuardarDatosHoja_Admision() {

        String sql;

        int idCiudad = ControlLlavePrimaria();
        conectar cc = new conectar();
        Connection cn = cc.conexion();

        sql = "INSERT INTO admision_ciudad (idCiudad,Nombre) VALUES (?,?) ";
        String sNombre = txtNombre.getText();
        try {
            PreparedStatement pst = (PreparedStatement) cn.prepareStatement(sql);

            pst.setInt(1, idCiudad);
            pst.setString(2, sNombre);

            int n = pst.executeUpdate();
            if (n > 0) {
            }
            cn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al guardar " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnAgregarCiudad = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 240));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 300, -1));

        jLabel1.setText("Coloque nombre a buscar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 140, 20));

        lblTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 90, 20));

        btnAgregarCiudad.setText("Agregar Ciudad");
        btnAgregarCiudad.setToolTipText("");
        btnAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistrosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRegistrosMouseClicked

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        cargar(txtNombre.getText());
    }//GEN-LAST:event_txtNombreKeyTyped

    private void btnAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCiudadActionPerformed
        // TODO add your handling code here:

        int i = 1;
        boolean bExiste = false;
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String sql = "SELECT MAX(idCiudad) as NumMaximo FROM admision_ciudad";
        try {
            java.sql.Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                i = rs.getInt("NumMaximo");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al Consultar tipo " + ex);
            ex.printStackTrace();
        }
        for (int j = 0; j <= i; j++) {

            String sql1 = "SELECT Nombre FROM albergue_sanvicente.admision_ciudad ";

            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql1);

                while (rs.next()) {
                    if (txtNombre.getText().equals(rs.getString("Nombre"))) {
                        bExiste = true;
                    } else {
                        bExiste = false;
                    }

                }
                if (bExiste == false) {
                    GuardarDatosHoja_Admision();
                    cargar("");
                } else {
                    JOptionPane.showMessageDialog(null, "Ya existe esa ciudad");
                }
                st.close();
                cn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al Consultar tipo " + ex);
            }
        }


    }//GEN-LAST:event_btnAgregarCiudadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Ciudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Ciudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Ciudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Ciudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Ciudad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCiudad;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblTipo;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
