/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admision;

import static Admision.Hoja_Admision.lblFoto;
import Herramientas.conectar;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luis
 */
public class Busqueda_Huesped extends javax.swing.JFrame {

    // VARIABLES GLOBALES
    DefaultTableModel model;
   public byte[] foto;
   
   
    public Busqueda_Huesped() {
        initComponents();
        cargar("");

    }

       public byte[] getFoto() {
        return foto;
    }

    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    void cargar(String sValor) {
        String[] titulos = {"Numero Huesped", "Nombre", "Tutor"};
        String[] registros = new String[4];

        String sql = "SELECT * FROM albergue_sanvicente.admision_hojaadmision WHERE CONCAT( idNumHuesped, ' ', NombreNiño,' ',Apellido_PaternoNiño,' ',Apellido_MaternoNiño,' ',NombreTutor )LIKE '%" + sValor + "%'";
        model = new DefaultTableModel(null, titulos);
        conectar cc = new conectar();
        Connection cn = cc.conexion();

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                registros[0] = rs.getString("idNumHuesped");

                registros[1] = rs.getString("NombreNiño") + " " + rs.getString("Apellido_PaternoNiño") + " " + rs.getString("Apellido_MaternoNiño");
                registros[2] = rs.getString("NombreTutor");

                model.addRow(registros);
            }
            tblRegistros.setModel(model);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnColocarDatos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 240));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 300, -1));

        jLabel1.setText("Coloque nombre a buscar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 140, 20));

        lblTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 30, 90, 20));

        btnColocarDatos.setText("Insertar Datos");
        btnColocarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColocarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnColocarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        cargar(txtNombre.getText());
    }//GEN-LAST:event_txtNombreKeyTyped

    private void tblRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistrosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRegistrosMouseClicked

    private void btnColocarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColocarDatosActionPerformed
        // TODO add your handling code here:
        if (tblRegistros.getSelectedRow() != -1) {

            if (lblTipo.getText().equals("FichaIngreso")) {

                String sql = "SELECT * FROM albergue_sanvicente.admision_hojaadmision WHERE idNumHuesped = " + tblRegistros.getValueAt(tblRegistros.getSelectedRow(), 0);

                conectar cc = new conectar();
                Connection cn = cc.conexion();

                try {
                    Statement st = cn.createStatement();
                    ResultSet rs = st.executeQuery(sql);

                    while (rs.next()) {
                        FichaIngreso.txtNombreNiño.setText(rs.getString(2));
                        FichaIngreso.cbxEdadNiño.setSelectedItem(rs.getString(5));
                        FichaIngreso.txtApellidoPaternoNiño.setText(rs.getString(3));
                        FichaIngreso.txtApellidoMaternoNiño.setText(rs.getString(4));
                        FichaIngreso.txtTutor1.setText(rs.getString(16));
                        FichaIngreso.cbxEdadTutor1.setSelectedItem(rs.getString(17));
                        FichaIngreso.txtDiscapacidad.setText(rs.getString(10));
                        FichaIngreso.txtServicioMedico.setText(rs.getString(11));
                        FichaIngreso.txtDomicilio.setText(rs.getString(18));
                        FichaIngreso.txtProcedencia.setText(rs.getString(19));
                        FichaIngreso.txtTutor1.setText(rs.getString(16));
                        FichaIngreso.txtTelefono.setText(rs.getString(21));
                        FichaIngreso.txtCelular.setText(rs.getString(22));
                    }
                    st.close();
                    cn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error al Consultar tipo " + ex);
                }
                this.dispose();

            } else if (lblTipo.getText().equals("HojaAdmision")) {
                String sNumHuesped = String.valueOf(tblRegistros.getValueAt(tblRegistros.getSelectedRow(), 0));
            String sql = "SELECT * FROM albergue_sanvicente.admision_hojaadmision WHERE idNumHuesped = " + sNumHuesped;

            conectar cc = new conectar();
            Connection cn = cc.conexion();

            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);

                while (rs.next()) {
                    Hoja_Admision.txtNombreNiño.setText(rs.getString(2));
                    Hoja_Admision.txtApPaternoNiño.setText(rs.getString(3));
                    Hoja_Admision.txtApMaternoNiño.setText(rs.getString(4));
                    Hoja_Admision.cbxEdadNiño.setSelectedItem(rs.getString(5));
                    Hoja_Admision.cbxSangre.setSelectedItem(rs.getString(6));
                    //Hoja_Admision.jfcFechaNiño.setDate(rs.getDate(7));//----------------------------VER SI NO VOLTEA LA FECHA
                    System.out.println(rs.getString(7));
                    Hoja_Admision.cbxEscolaridad.setSelectedItem(rs.getString(8));
                    Hoja_Admision.txtCorreo.setText(rs.getString(9));
                    Hoja_Admision.txtDiagnostico.setText(rs.getString(10));
                    Hoja_Admision.txtServicioMedico.setText(rs.getString(11));
                    Hoja_Admision.txtAlergia.setText(rs.getString(12));
                    Hoja_Admision.txtTerapias.setText(rs.getString(13));
                    Hoja_Admision.txtDuracion.setText(rs.getString(14));
                    Hoja_Admision.txpObservaciones1.setText(rs.getString(15));
                    Hoja_Admision.txtNombreTutor.setText(rs.getString(16));
                    Hoja_Admision.cbxEdadTutor.setSelectedItem(rs.getString(17));
                    Hoja_Admision.txtDireccionTutor.setText(rs.getString(18));
                    Hoja_Admision.cbxMunicipio.setSelectedItem(rs.getString(19));
                    Hoja_Admision.txtCPTutor.setText(rs.getString(20));
                    Hoja_Admision.txtTelCasaTutor.setText(rs.getString(21));
                    Hoja_Admision.txtCelTutor.setText(rs.getString(22));
                    Hoja_Admision.txtFamiliar1.setText(rs.getString(23));
                    Hoja_Admision.txtTelFamiliar1.setText(rs.getString(24));
                    Hoja_Admision.txtCelFamiliar1.setText(rs.getString(25));
                    Hoja_Admision.txtFamiliar2.setText(rs.getString(26));
                    Hoja_Admision.txtTelFamiliar2.setText(rs.getString(27));
                    Hoja_Admision.txtCelFamiliar2.setText(rs.getString(28));
                    Hoja_Admision.txtAcompañante1.setText(rs.getString(29));
                    Hoja_Admision.txtParentesco1.setText(rs.getString(30));
                    Hoja_Admision.cbxEdadAcompañante1.setSelectedItem(rs.getString(31));
                    Hoja_Admision.txtAcompañante2.setText(rs.getString(32));
                    Hoja_Admision.txtParentesco2.setText(rs.getString(33));
                    Hoja_Admision.cbxEdadAcompañante2.setSelectedItem(rs.getString(34));
                    Hoja_Admision.txpObservaciones2.setText(rs.getString(35));
                    Hoja_Admision.txtTiempoAlbergue.setText(rs.getString(36));
                    Hoja_Admision.txtTiempoCRIT.setText(rs.getString(37));
                    //SET BITS DE IMAGEN
                    setFoto(rs.getBytes("FotoNiño"));
                    byte[] bi = getFoto();
                    BufferedImage image = null;
                    InputStream in = new ByteArrayInputStream(bi);
                    image = ImageIO.read(in);
                    ImageIcon imgi = new ImageIcon(image.getScaledInstance(140, 150, 0));
                    Hoja_Admision.lblFoto.setIcon(imgi);
                }
                st.close();
                cn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al Consultar tipo " + ex);
            } catch (IOException ex) {
                Logger.getLogger(Busqueda_Huesped.class.getName()).log(Level.SEVERE, null, ex);
            }
              this.dispose();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debes seleccionar algun huesped");
        }
    }//GEN-LAST:event_btnColocarDatosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda_Huesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda_Huesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda_Huesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda_Huesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda_Huesped().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColocarDatos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblTipo;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
